### ISSUE TITLE
[Bug]: "from spectrafit.plugins import notebook as nb" produces an error

### ISSUE THREAD

**Issue by olafruediger** [Anselmoo/spectrafit#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_324/384473029.py in <module>
----> 1 from spectrafit.plugins import notebook as nb

~\Anaconda3\lib\site-packages\spectrafit\plugins\notebook.py in <module>
     14 import tomli_w
     15 
---> 16 from dtale import show as dtale_show
     17 from IPython.display import display
     18 from IPython.display import display_markdown

~\Anaconda3\lib\site-packages\dtale\__init__.py in <module>
      1 import warnings
      2 
----> 3 from flask import Blueprint
      4 
      5 with warnings.catch_warnings():

~\Anaconda3\lib\site-packages\flask\__init__.py in <module>
     12 # utilities we import from Werkzeug and Jinja2 that are unused
     13 # in the module but are exported as public interface.
---> 14 from jinja2 import escape
     15 from jinja2 import Markup
     16 from werkzeug.exceptions import abort

ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\ruediger\Anaconda3\lib\site-packages\jinja2\__init__.py)

### ⚙️ Environment

```markdown
- OS:Windows10
- Python:3.8.8
- spectrafit:0.16.5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anselmoo** [comment]
@olafruediger  for letting me known. I actually couldn't reproduce the error:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/13209783/225723753-41766f0e-7bd5-449d-a8ba-2e8aea678150.png">

Do you install spectrafit via:

```shell
conda install spectrafit
```

or as **required**

```shell
conda install spectrafit-all
```

or:

```shell
conda install spectrafit-jupyter
```

The reason for splitting the conda-package into sub-packages is the required packages with 296MB.

Please also check: https://github.com/conda-forge/spectrafit-feedstock

**Comment by Anselmoo** [comment]
It will be updated in the docs

**Comment by Anselmoo** [comment]
It's actually mentioned right here

https://anselmoo.github.io/spectrafit/v1.0.0a7/interface/installation/#via-environment
